---
# handlers file for nginx
#- name: start and enable nginx CentOS
- name: start nginx
  become: true
  systemd: 
    name: nginx
    enabled: yes
    state: started
    daemon-reload: yes

- name: stop nginx
  become: true
  service: name=nginx state=stopped

